version: '3.8'

services:
  nginx:
  #Utilitzem servei Nginx setmana 8
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-nginx
    ports:
      - "${NGINX_PORT}:80"
    #Volum per a dades persistents
    volumes:
      - nginx_data:/usr/share/nginx/html
    depends_on:
      - backend

  # Utilitzem backend simple setmana 8
  backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: python-backend
    ports:
      - "${BACKEND_PORT}:3000"

#Declarem volum perquè sobrevisqui als reinicis
volumes:
  nginx_data:
