name: integracio continua GSX

on:
  push:
    branches: [ "main", "setmana11" ]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: ./terraform
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

  docker-build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Backend
      run: |
        cd docker-compose
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-simple:v1 -f Dockerfile.app .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-simple:v1
    - name: Build and push Nginx
      run: |
        cd docker-compose
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx-gsx:v1 -f Dockerfile .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx-gsx:v1
